### ISSUE TITLE
Create Page Using Html

### ISSUE THREAD

**Issue by AbdullahGalalMohamed** [AbdullahGalalMohamed/SE2018G06#1]
deadline 4 days

**Comment by a7medfawzy97** [comment]
[My First Html page.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2479618/My.First.Html.page.txt)

**Comment by a7medfawzy97** [comment]
[login page.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2479781/login.page.txt)

**Comment by sanody** [comment]
[first.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2480674/first.txt)

**Comment by abdelhadyahmed** [comment]
[signin.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2484105/signin.txt)

**Comment by marina-fares** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="Welcome">
    <style>
		body{background-color:#b3d1ff;
			 background-gardient:20px;
			 margin:0;
   			 padding:0;
    		 position:relative;
			 }
		ul {
		     list-style-type: none;
 		     margin: 0;
  		     padding: 0;
 		     overflow: hidden;
 		     background-color:white;
 		     width:100%;
			}

		li {
		     float: right;
				}

		li a {
		    display: inline-block;
		    color:black;
 		    text-align: center;
 		    padding: 14px 16px;
 		    text-decoration: none;
}
		li a:hover{background-color:#99ff99}

		.div1{ margin: auto;
		       width: 50%;
		       text-align:center;
 			   font-size:50px;
              font-style:italic;
              position: absolute;
              position: absolute;
              top: 150px;
              right: 16px;
          }
      fieldset{width:36%;
             float:left;
             overflow:hidden;
             padding:30px 30px;
             margin:16px;
             border-radius:10px;
             box-shadow:5px 10px 12px;
           }
         input{padding:8px;
         	   border-radius:10px;
               margin:8px;
               width:90%;
         	   }

span{
font-size:22px;
text-align:center;
overflow:hidden;

padding:15px 100px;
margin:0;
top:0;
}
</style>
</head>
<body>


<ul>
  <li><a href="#"><bold>Home<me</a></li>
  <li><a href="#">About Us</a></li>
  <li><a href="#">News</a></li>
  <li><a href="#">Contacts</a></li>
</ul>


<fieldset >
<form>
  <span >SignIn</span> 
  <br>
  <input type="text" name="username" value="user name"><br>
  <br>
  <input type="password" name="psw" value="password"><br>
  <input type="submit" value="Submit" style="padding:5px;width:100%">
</form>
<div><a href="#"  style="color:black;">forget passeword<a></div>
<div><a href="#" style="color:black;">Don't have an account</a></div>
</fieldset>
<div class="div1">Don't listen to what they see ..Go & See
</div>

</body>
</html>

**Comment by marina-fares** [comment]
[my_first_project.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2485140/my_first_project.txt)

**Comment by AbdullahGalalMohamed** [comment]
[SingUpPage.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2485350/SingUpPage.txt)

**Comment by emadmasri40** [comment]
[login.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2489341/login.txt)

**Comment by Alaa-Atef** [comment]
[First html example.txt](https://github.com/AbdullahGalalMohamed/SE2018G06/files/2489347/First.html.example.txt)
